name: Build and Publish Refiner Service Docker Image

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git reference to checkout (branch, tag, or SHA)'
        required: true
        default: 'main'
      stable_release:
        description: 'Mark this build as a stable release'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Get current commit SHA
        id: current_sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Get branch name
        id: branch_name
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            BRANCH=${GITHUB_REF#refs/heads/}
          else
            BRANCH=$(git rev-parse --abbrev-ref HEAD)
          fi
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SERVICE_ACCOUNT_PAT }}

      - name: Set Docker image tags
        id: tags
        run: |
          TAGS="${{ vars.DOCKERHUB_USERNAME }}/vana-refinement-service:${{ steps.current_sha.outputs.sha }}"

          # Add branch-specific tags
          if [[ "${{ steps.branch_name.outputs.branch }}" == "main" ]]; then
            TAGS="$TAGS,${{ vars.DOCKERHUB_USERNAME }}/vana-refinement-service:main-${{ steps.current_sha.outputs.sha }}"
            TAGS="$TAGS,${{ vars.DOCKERHUB_USERNAME }}/vana-refinement-service:mainnet-latest"
          elif [[ "${{ steps.branch_name.outputs.branch }}" == "dev" ]]; then
            TAGS="$TAGS,${{ vars.DOCKERHUB_USERNAME }}/vana-refinement-service:dev-${{ steps.current_sha.outputs.sha }}"
            TAGS="$TAGS,${{ vars.DOCKERHUB_USERNAME }}/vana-refinement-service:moksha-latest"
          fi

          # Add latest tag for main branch
          if [[ "${{ steps.branch_name.outputs.branch }}" == "main" ]]; then
            TAGS="$TAGS,${{ vars.DOCKERHUB_USERNAME }}/vana-compute-engine:latest"
          fi
          
          if [[ "${{ github.event.inputs.stable_release }}" == "true" ]]; then
            TAGS="$TAGS,${{ vars.DOCKERHUB_USERNAME }}/vana-compute-engine:stable"
          fi
          
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          echo "Generated tags: $TAGS"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.tags.outputs.tags }}